<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PelayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pelayanans')->insert(
            [
                // Bulan Sebelumnya
                [
                    "id_balita" => 1,
                    "nik_balita" => "2110051001990001",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 74.2,
                    "bb" => 9,
                    "lingkar_kepala" => 45,
                    "usia" => 13,
                    "verif" => "y",
                    "bbu" => -0.18,
                    "tbu" => -0.46,
                ],
                [
                    "id_balita" => 2,
                    "nik_balita" => "2108151002990004",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 74.2,
                    "bb" => 9.2,
                    "lingkar_kepala" => 46,
                    "usia" => 15,
                    "verif" => "y",
                    "bbu" => -1.18,
                    "tbu" => -2.04,
                ],
                [
                    "id_balita" => 3,
                    "nik_balita" => "2106221003990007",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 66.3,
                    "bb" => 7.5,
                    "lingkar_kepala" => 40,
                    "usia" => 5,
                    "verif" => "y",
                    "bbu" => -0.63,
                    "tbu" => 0.05,
                ],
                [
                    "id_balita" => 4,
                    "nik_balita" => "2105111004990010",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 76.9,
                    "bb" => 9.5,
                    "lingkar_kepala" => 47.2,
                    "usia" => 18,
                    "verif" => "y",
                    "bbu" => -1.73,
                    "tbu" => -2.33,
                ],
                [
                    "id_balita" => 5,
                    "nik_balita" => "2103271005990013",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 69,
                    "bb" => 8,
                    "lingkar_kepala" => 44.2,
                    "usia" => 8,
                    "verif" => "y",
                    "bbu" => 0.11,
                    "tbu" => 0.13,
                ],
                [
                    "id_balita" => 6,
                    "nik_balita" => "2011181006990016",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 73.2,
                    "bb" => 8.5,
                    "lingkar_kepala" => 42,
                    "usia" => 12,
                    "verif" => "y",
                    "bbu" => -1.60,
                    "tbu" => -1.17,
                ],
                [
                    "id_balita" => 7,
                    "nik_balita" => "2009091007990019",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 72.2,
                    "bb" => 8.5,
                    "lingkar_kepala" => 41.7,
                    "usia" => 10,
                    "verif" => "y",
                    "bbu" => -0.50,
                    "tbu" => 0.20,
                ],
                [
                    "id_balita" => 8,
                    "nik_balita" => "2007141008990022",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 82.2,
                    "bb" => 10.5,
                    "lingkar_kepala" => 46,
                    "usia" => 16,
                    "verif" => "y",
                    "bbu" => -0.45,
                    "tbu" => 0.69,
                ],
                [
                    "id_balita" => 9,
                    "nik_balita" => "2004301009990025",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 66,
                    "bb" => 6.7,
                    "lingkar_kepala" => 40,
                    "usia" => 7,
                    "verif" => "y",
                    "bbu" => -2.56,
                    "tbu" => -1.45,
                ],
                [
                    "id_balita" => 10,
                    "nik_balita" => "2002191010990028",
                    'tgl_pelayanan' => '2023-11-02',
                    "tb" => 70.5,
                    "bb" => 8.2,
                    "lingkar_kepala" => 42,
                    "usia" => 9,
                    "verif" => "y",
                    "bbu" => -1.00,
                    "tbu" => -0.87,
                ],

                // Bulan ini
                [
                    "id_balita" => 1,
                    "nik_balita" => "2110051001990001",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 76.4,
                    "bb" => 9.4,
                    "lingkar_kepala" => 46,
                    "usia" => 14,
                    "verif" => "y",
                    "bbu" => -0.36,
                    "tbu" => -0.15,
                ],
                [
                    "id_balita" => 2,
                    "nik_balita" => "2108151002990004",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 76.2,
                    "bb" => 10.2,
                    "lingkar_kepala" => 46.2,
                    "usia" => 16,
                    "verif" => "y",
                    "bbu" => -0.45,
                    "tbu" => -1.62,
                ],
                [
                    "id_balita" => 3,
                    "nik_balita" => "2106221003990007",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 67.6,
                    "bb" => 7.9,
                    "lingkar_kepala" => 40.5,
                    "usia" => 6,
                    "verif" => "y",
                    "bbu" => -1.13,
                    "tbu" => -0.29,
                ],
                [
                    "id_balita" => 4,
                    "nik_balita" => "2105111004990010",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 79.8,
                    "bb" => 9.8,
                    "lingkar_kepala" => 47.5,
                    "usia" => 19,
                    "verif" => "y",
                    "bbu" => -1.91,
                    "tbu" => -1.56,
                ],
                [
                    "id_balita" => 5,
                    "nik_balita" => "2103271005990013",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 69.7,
                    "bb" => 8.2,
                    "lingkar_kepala" => 44.2,
                    "usia" => 9,
                    "verif" => "y",
                    "bbu" => -0.22,
                    "tbu" => -0.46,
                ],
                [
                    "id_balita" => 6,
                    "nik_balita" => "2011181006990016",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 74.3,
                    "bb" => 8.7,
                    "lingkar_kepala" => 42.2,
                    "usia" => 13,
                    "verif" => "y",
                    "bbu" => -1.73,
                    "tbu" => -1.21,
                ],
                [
                    "id_balita" => 7,
                    "nik_balita" => "2009091007990019",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 72.8,
                    "bb" => 8.7,
                    "lingkar_kepala" => 41.9,
                    "usia" => 11,
                    "verif" => "y",
                    "bbu" => -0.70,
                    "tbu" => -0.32,
                ],
                [
                    "id_balita" => 8,
                    "nik_balita" => "2007141008990022",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 83.2,
                    "bb" => 11,
                    "lingkar_kepala" => 46.2,
                    "usia" => 17,
                    "verif" => "y",
                    "bbu" => 0.27,
                    "tbu" => 0.69,
                ],
                [
                    "id_balita" => 9,
                    "nik_balita" => "2004301009990025",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 67.2,
                    "bb" => 6.9,
                    "lingkar_kepala" => 40.5,
                    "usia" => 8,
                    "verif" => "y",
                    "bbu" => -2.89,
                    "tbu" => -1.64,
                ],
                [
                    "id_balita" => 10,
                    "nik_balita" => "2002191010990028",
                    'tgl_pelayanan' => '2023-12-03',
                    "tb" => 73.3,
                    "bb" => 9.2,
                    "lingkar_kepala" => 42.5,
                    "usia" => 10,
                    "verif" => "y",
                    "bbu" => -0.20,
                    "tbu" => -0.13,
                ],
            ]
        );
    }
}
