<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PelayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pelayanans')->insert(
            [
                // Bulan Sebelumnya
                [
                    "id_balita" => 1,
                    "nik_balita" => "2110051001990001",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 72,
                    "bb" => 9,
                    "lingkar_kepala" => 45,
                    "usia" => 11,
                    "verif" => "y",
                    "bbu" => -0.40,
                    "tbu" => -1.09,
                ],
                [
                    "id_balita" => 2,
                    "nik_balita" => "2108151002990004",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 80,
                    "bb" => 11,
                    "lingkar_kepala" => 46,
                    "usia" => 13,
                    "verif" => "y",
                    "bbu" => 1.00,
                    "tbu" => 1.29,
                ],
                [
                    "id_balita" => 3,
                    "nik_balita" => "2106221003990007",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 57.5,
                    "bb" => 6.4,
                    "lingkar_kepala" => 47,
                    "usia" => 3,
                    "verif" => "y",
                    "bbu" => -0.57,
                    "tbu" => -2.20,
                ],
                [
                    "id_balita" => 4,
                    "nik_balita" => "2105111004990010",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 78.2,
                    "bb" => 11,
                    "lingkar_kepala" => 48,
                    "usia" => 16,
                    "verif" => "y",
                    "bbu" => 0.45,
                    "tbu" => -0.85,
                ],
                [
                    "id_balita" => 5,
                    "nik_balita" => "2103271005990013",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 62,
                    "bb" => 7.0,
                    "lingkar_kepala" => 49,
                    "usia" => 6,
                    "verif" => "y",
                    "bbu" => -1.13,
                    "tbu" => -2.67,
                ],
                [
                    "id_balita" => 6,
                    "nik_balita" => "2011181006990016",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 69.5,
                    "bb" => 7.8,
                    "lingkar_kepala" => 50,
                    "usia" => 10,
                    "verif" => "y",
                    "bbu" => -2.20,
                    "tbu" => -1.87,
                ],
                [
                    "id_balita" => 7,
                    "nik_balita" => "2009091007990019",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 70.6,
                    "bb" => 8.2,
                    "lingkar_kepala" => 51,
                    "usia" => 8,
                    "verif" => "y",
                    "bbu" => -0.67,
                    "tbu" => -0.27,
                ],
                [
                    "id_balita" => 8,
                    "nik_balita" => "2007141008990022",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 77.5,
                    "bb" => 10.9,
                    "lingkar_kepala" => 52,
                    "usia" => 14,
                    "verif" => "y",
                    "bbu" => -0.09,
                    "tbu" => -0.42,
                ],
                [
                    "id_balita" => 9,
                    "nik_balita" => "2004301009990025",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 66,
                    "bb" => 7.6,
                    "lingkar_kepala" => 53,
                    "usia" => 5,
                    "verif" => "y",
                    "bbu" => -0.63,
                    "tbu" => 0.05,
                ],
                [
                    "id_balita" => 10,
                    "nik_balita" => "2002191010990028",
                    'tgl_pelayanan' => '2023-09-17',
                    "tb" => 64.5,
                    "bb" => 5.6,
                    "lingkar_kepala" => 54,
                    "usia" => 7,
                    "verif" => "y",
                    "bbu" => -3.67,
                    "tbu" => -2.36,
                ],

                // Bulan ini
                [
                    "id_balita" => 1,
                    "nik_balita" => "2110051001990001",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 72.5,
                    "bb" => 9.4,
                    "lingkar_kepala" => 45,
                    "usia" => 12,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 2,
                    "nik_balita" => "2108151002990004",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 80.3,
                    "bb" => 12,
                    "lingkar_kepala" => 46,
                    "usia" => 14,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 3,
                    "nik_balita" => "2106221003990007",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 57.9,
                    "bb" => 7.0,
                    "lingkar_kepala" => 47,
                    "usia" => 4,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 4,
                    "nik_balita" => "2105111004990010",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 78.8,
                    "bb" => 11.5,
                    "lingkar_kepala" => 48,
                    "usia" => 17,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 5,
                    "nik_balita" => "2103271005990013",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 62.5,
                    "bb" => 7.4,
                    "lingkar_kepala" => 49,
                    "usia" => 7,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 6,
                    "nik_balita" => "2011181006990016",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 70,
                    "bb" => 8.2,
                    "lingkar_kepala" => 50,
                    "usia" => 11,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 7,
                    "nik_balita" => "2009091007990019",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 71.1,
                    "bb" => 8.4,
                    "lingkar_kepala" => 51,
                    "usia" => 9,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 8,
                    "nik_balita" => "2007141008990022",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 78.0,
                    "bb" => 11.4,
                    "lingkar_kepala" => 52,
                    "usia" => 15,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 9,
                    "nik_balita" => "2004301009990025",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 67,
                    "bb" => 8.0,
                    "lingkar_kepala" => 53,
                    "usia" => 6,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
                [
                    "id_balita" => 10,
                    "nik_balita" => "2002191010990028",
                    'tgl_pelayanan' => '2023-10-15',
                    "tb" => 65.5,
                    "bb" => 5.9,
                    "lingkar_kepala" => 54,
                    "usia" => 8,
                    "verif" => "n",
                    "bbu" => null,
                    "tbu" => null,
                ],
            ]
        );
    }
}
